// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconDashiconsFacebookAlt: typeof import('~icons/dashicons/facebook-alt.jsx')['default']
  const IconDashiconsInstagram: typeof import('~icons/dashicons/instagram.jsx')['default']
  const IconDashiconsTwitter: typeof import('~icons/dashicons/twitter.jsx')['default']
}
